version: "3.8"

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - 5436:5432

  web:
    build: .
    ports:
      - 4000:5000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

volumes: 
  dbdata:
